### ISSUE TITLE
Fatal error: Uncaught exception

### ISSUE THREAD

**Issue by TheSkyHeart** [OnApp/OnApp-WHMCS-UsersModule#11]
Hi,

we have this Fatal Error when we create a Product for onappuser 

Fatal error: Uncaught exception 'Exception' with message 'The wrapper class 'OnApp_Role' does not support OnApp version '0'' in /var/www/includes/wrapper/OnApp.php:751 Stack trace: #0 /var/www/includes/wrapper/Role.php(115): OnApp->initFields(0, 'OnApp_Role') #1 /var/www/includes/wrapper/OnApp.php(672): OnApp_Role->initFields(0) #2 /var/www/modules/servers/onappusers/onappusers.php(663): OnApp->auth('https://185.76....', 'admin', 'changeme') #3 /var/www/modules/servers/onappusers/onappusers.php(638): OnApp_UserModule->getOnAppObject('OnApp_Role') #4 /var/www/modules/servers/onappusers/onappusers.php(91): OnApp_UserModule->getRoles() #5 /var/www/admin/configproducts.php(0): onappusers_ConfigOptions(Array) #6 {main} Next exception 'Exception' with message 'The wrapper class 'OnApp_Role' does not support OnApp version '0'' in /var/www/includes/classes/WHMCS/Terminus.php:0 Stack trace: #0 [internal function]: WHMCS_Terminus->whmcsExceptionHandler(Object(Exception)) #1 {main} thrown in /var/www/includes/classes/WHMCS/Terminus.php on line 0

**Comment by Lev-Bartashevsky** [comment]
Something wrong with getting OnApp version.
Does user 'admin' has permission to get OnApp version?
What is response for https://185.76..../version.json with user 'admin'?

**Comment by TheSkyHeart** [comment]
Thanks Lev,

that helped me find the problem, it was a problem in our httpd.conf file 


thanks a lot

**Comment by Lev-Bartashevsky** [comment]
You are welcome)
