### ISSUE TITLE
Edit Product > Module Settings

### ISSUE THREAD

**Issue by apetrocelli** [OnApp/OnApp-WHMCS-UsersModule#12]
Unable to save checkboxes values in WHMCS 6.0.1

as you can see in screenshot, after "Save Changes" checkbox values selected are not saved...

Thanks a lot

![capture](https://cloud.githubusercontent.com/assets/13481129/8870711/54dc3284-31f0-11e5-8bd8-a3b645dff0e5.PNG)

**Comment by Lev-Bartashevsky** [comment]
Please update code to https://github.com/OnApp/OnApp-WHMCS-UsersModule/releases/tag/v3.4.5.1
