### ISSUE TITLE
Stats not appearing in WHMCS product details. 

### ISSUE THREAD

**Issue by ephost** [OnApp/OnApp-WHMCS-UsersModule#13]
Line 553 of onappusers.php contains a hard coded reference to the WHMCS default template "six". If you have customized your theme and used a copy of v6 then you need to update that line to match your template's name. Perhaps a configuration file is needed in case someone is using a v5 template with v6 or some other configuration.

**Comment by Lev-Bartashevsky** [comment]
It's temporary solutions.
We are trying to find the best way to allow customization not just in that line but also in the module client area template.

**Comment by ephost** [comment]
Thank you for the info.
