### ISSUE TITLE
Invoices not being generated with WHMCS v6 and OnApp 3.5

### ISSUE THREAD

**Issue by ephost** [OnApp/OnApp-WHMCS-UsersModule#14]
Invoices not being generated with WHMCS v6 (with v6 template) and OnApp 3.5 with PHP Wrapper (older and newer) and latest Users Module v3.4.5.1. 

Any advice on specific versions needed for this configuration while we wait for the OnApp v4 upgrade? 

Also the documentation for the Users Module seem out of date and reference two CRON jobs while only one is being displayed in the docs.

**Comment by Lev-Bartashevsky** [comment]
Thanks for reporting.
Do you have any error log?

**Comment by ephost** [comment]
That was fast :). No, the logs don't seem to generate. Probably due to directory path references (Windows Server in this case). I commented out the EOL statement and tried to run from the browser and gettign 500 error:

Notice: Undefined index: argv in C:\somedir\someaccount\somedomain\wwwroot\account\modules\servers\onappusers\cronjobs\common.php on line 26

Warning: require_once(C:\somedir\someaccount\somedomain\wwwroot\account\modules\servers\onappusers\cronjobs\dbconnect.php): failed to open stream: No such file or directory in C:\HostingSpaces\ephost1\ephost.com\wwwroot\account\modules\servers\onappusers\cronjobs\common.php on line 276

Fatal error: require_once(): Failed opening required 'C:\somedir\someaccount\somedomain\wwwroot\account\modules\servers\onappusers\cronjobs\dbconnect.php' (include_path='.;C:\php\pear') in C:\HostingSpaces\ephost1\ephost.com\wwwroot\account\modules\servers\onappusers\cronjobs\common.php on line 276

**Comment by Lev-Bartashevsky** [comment]
invoice generation stuff is designed to run in cli-mode (console) only.
anyway it seems to be Windows-related issue.
I'll check it tomorrow.

**Comment by ephost** [comment]
Thank you. Where is this dbconnect.php file the error references? I am not seeing it in WHMCS v6 but I do see it in WHMCS v5 in the root WHMCS install folder.

**Comment by Lev-Bartashevsky** [comment]
dbconnect.php was removed in v6.
the problem seems to be in detecting root path on Windows and/or running script in browser instead of cli-mode.
check https://github.com/OnApp/OnApp-WHMCS-UsersModule/blob/master/modules/servers/onappusers/cronjobs/common.php#L272
and https://github.com/OnApp/OnApp-WHMCS-UsersModule/blob/master/modules/servers/onappusers/cronjobs/common.php#L26

**Comment by ephost** [comment]
Okay that makes sense if $ _ SERVER[ 'argv' ][ 0 ]  is not available when running in browser. Can I temporarily/permanently hard code the path (line 26) for my environment and run in the CLI?

If so, would that be the root of the site, the root of WHMCS or to root of one of the WHMCS directories...? 

Don't mean to press but I need to generate invoices for July.

**Comment by Lev-Bartashevsky** [comment]
SERVER[ 'argv' ] should be propagated correctly if run in CLI.
anyway You are free to do whatever you want with code on your server)

root should point to WHMCS root directory. and I strongly recommend to run tests first, https://github.com/OnApp/OnApp-WHMCS-UsersModule/wiki/2.-Setting-up-cronjobs#testing-invoice-generator

**Comment by ephost** [comment]
Yes, it used to work fine in the CLI. 

That's the link that seems to reference two CRON jobs but only shows one. Is there supposed to be a job for stats collection and one for monthly invoices? Is stats collection unneeded now?

"{WHMCS} is the full path to your WHMCS directory.
First command is usage statistics collector.
Second one is invoice generator."

**Comment by Lev-Bartashevsky** [comment]
stats collection was removed quite long time ago.
could not you provide link where you found mention about it?
on https://github.com/OnApp/OnApp-WHMCS-UsersModule/wiki/2.-Setting-up-cronjobs I see just one cronjob.

**Comment by ephost** [comment]
There is only one cron job but the text says "First command is usage statistics collector. Second one is invoice generator."

https://github.com/OnApp/OnApp-WHMCS-UsersModule/wiki/2.-Setting-up-cronjobs

**Comment by Lev-Bartashevsky** [comment]
Thanks for paying attention to this point, fixed.

**Comment by chetanmane** [comment]
Hi,
We are getting same error for generating invoice and for test cron job see error below
[28-Feb-2016 13:28:33 UTC] PHP Notice:  Undefined index: argv in /home/chetan4378/public_html/stack/modules/servers/onappusers/cronjobs/common.php on line 26
[28-Feb-2016 13:28:33 UTC] PHP Warning:  require_once(/home/chetan4378/public_html/stack/modules/servers/onappusers/cronjobs/dbconnect.php): failed to open stream: No such file or directory in /home/chetan4378/public_html/stack/modules/servers/onappusers/cronjobs/common.php on line 275
[28-Feb-2016 13:28:33 UTC] PHP Fatal error:  require_once(): Failed opening required '/home/chetan4378/public_html/stack/modules/servers/onappusers/cronjobs/dbconnect.php' (include_path='.:/opt/alt/php55/usr/share/pear:/opt/alt/php55/usr/share/php') in /home/chetan4378/public_html/stack/modules/servers/onappusers/cronjobs/common.php on line 275
how to resolve that
Thanks in advance

**Comment by ephost** [comment]
Thank you for writing. I will be out-of-the-country on vacation from February 1st to March 3rd with intermittent access to email and telephone.

If you require immediate assistance please call my colleagues Tegan King at 858-433-2818 at extension 140 or Morgan Lunsford at extension 180 who can reach me with any questions or emergencies. 

Otherwise, please redirect your email to support@ephost.com and one of our technical support representatives will assist 24/7. 

I will reply your email when I return. 

Thank you!
  
Joe Rebis
CEO, EPhost, Inc.
