### ISSUE TITLE
php 7 compability?

### ISSUE THREAD

**Issue by ebaadnes** [OnApp/OnApp-WHMCS-UsersModule#15]
Any plans to upgrade to php7 compability?

**Comment by mattiashallstrom** [comment]
I wonder this as well!
The module uses mysql_result which is deprecated since php 5.5 and removed in php 7

**Comment by prado1991** [comment]
WHMCS OnApp User module has php7 compatibility and there are no mysql_result in source code since module version - 3.7.2. 
There are some functions that looks like deprecated mysql functions but they are provided by WHMCS for compatibility.

**Comment by mattiashallstrom** [comment]
Thanks @prado1991 for the info. Didn't see the later versions, the last release is 3.7 (https://github.com/OnApp/OnApp-WHMCS-UsersModule/releases) that they created...

**Comment by prado1991** [comment]
fresh release:
https://github.com/OnApp/OnApp-WHMCS-UsersModule/releases/tag/v3.7.4
