### ISSUE TITLE
Check for do not suspend

### ISSUE THREAD

**Issue by isodude** [OnApp/OnApp-WHMCS-UsersModule#9]
We need to check for the do not suspend value in WHMCS, so that we can wait for payment a little while longer.

Doesn't seem like this is done at all?

**Comment by Lev-Bartashevsky** [comment]
This was done in the latest prerelease version.

**Comment by isodude** [comment]
Do you have a link to the commit regarding this? I would like to verify that it's in our current installation.

**Comment by isodude** [comment]
Any news regarding this?

**Comment by prado1991** [comment]
If you want to set your own due day, you can change WHMCS default due day:
Setup->Automation Settings->Billing Settings->Invoice Generation
